FROM public.ecr.aws/lambda/python:3.9

COPY requirements/requirements_app.txt .

RUN pip install --upgrade pip && pip install -r requirements_app.txt

COPY api/app api/app
COPY api/main.py api/main.py
COPY model/model.pkl model/model.pkl

# EXPOSE 8000 8080

CMD ["api.main.handler"]